### ISSUE TITLE
[Question]: rerank index IndexError: list index out of range

### ISSUE THREAD

**Issue by lambda7xx** [run-llama/llama_index#12323] opened 2024-03-27 13:55 UTC
i run the follow code
```
import nest_asyncio

nest_asyncio.apply()

import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.core.postprocessor import LLMRerank


from IPython.display import Markdown, display

import llama_index.core 

llama_index.core.set_global_handler("simple")

from llama_index.core import Settings
from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core.prompts import PromptTemplate
import torch 
from llama_index.core import VectorStoreIndex
from llama_index.core import  SimpleDirectoryReader

llm = HuggingFaceLLM(
    model_name="mistralai/Mistral-7B-Instruct-v0.1",
    tokenizer_name="mistralai/Mistral-7B-Instruct-v0.1",
    query_wrapper_prompt=PromptTemplate("<s>[INST] {query_str} [/INST] </s>\n"),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"torch_dtype": torch.bfloat16},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.2, "top_k": 5, "top_p": 0.95},
    device_map="auto",
)

# LLM (gpt-3.5-turbo)


Settings.llm = llm

embeddings = ["local:BAAI/bge-small-en-v1.5"]

Settings.embed_model = embeddings[0]

# Settings.chunk_overlap = 0
# Settings.chunk_size = 128

# load documents
import time
start = time.time()
documents = SimpleDirectoryReader(
    input_files=["./data/10k/lyft_2021.pdf"]
).load_data()
end = time.time()
print(f"duration:{end-start}")

index = VectorStoreIndex.from_documents(
    documents,
)


from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core import QueryBundle
import pandas as pd
from IPython.display import display, HTML
from copy import deepcopy


pd.set_option("display.max_colwidth", 1)

from llama_index.core.indices.utils import default_parse_choice_select_answer_fn



def get_retrieved_nodes(
    query_str, vector_top_k=10, reranker_top_n=3, with_reranker=False
):
    query_bundle = QueryBundle(query_str)
    # configure retriever
    retriever = VectorIndexRetriever(
        index=index,
        similarity_top_k=vector_top_k,
    )
    retrieved_nodes = retriever.retrieve(query_bundle)

    if with_reranker:

        reranker = LLMRerank(
            choice_batch_size=5,
            top_n=reranker_top_n,
            llm = Settings.llm,
        )
        retrieved_nodes = reranker.postprocess_nodes(
            retrieved_nodes, query_bundle
        )

    return retrieved_nodes


def pretty_print(df):
    return display(HTML(df.to_html().replace("\\n", "<br>")))


def visualize_retrieved_nodes(nodes) -> None:
    result_dicts = []
    for node in nodes:
        node = deepcopy(node)
        node.node.metadata = {}
        node_text = node.node.get_text()
        node_text = node_text.replace("\n", " ")

        result_dict = {"Score": node.score, "Text": node_text}
        result_dicts.append(result_dict)

    pretty_print(pd.DataFrame(result_dicts))



import time 
start = time.time()

new_nodes = get_retrieved_nodes(
    "What is Lyft's response to COVID-19?", vector_top_k=5, with_reranker=False
)


visualize_retrieved_nodes(new_nodes)

end = time.time()

print(f"************ first rerank, duration:{end - start }\n\n")

start = time.time()
new_nodes = get_retrieved_nodes(
    "What is Lyft's response to COVID-19?",
    vector_top_k=20,
    reranker_top_n=5,
    with_reranker=True,
)

visualize_retrieved_nodes(new_nodes)

end = time.time()

print(f"************ second rerank, duration:{end - start }\n\n")

start  =  time.time()

new_nodes = get_retrieved_nodes(
    "What initiatives are the company focusing on independently of COVID-19?",
    vector_top_k=5,
    with_reranker=False,
)


visualize_retrieved_nodes(new_nodes)


end = time.time()

print(f"************ third rerank, duration:{end - start }\n\n")

start  =  time.time()

new_nodes = get_retrieved_nodes(
    "What initiatives are the company focusing on independently of COVID-19?",
    vector_top_k=40,
    reranker_top_n=5,
    with_reranker=True,
)

visualize_retrieved_nodes(new_nodes)

end = time.time()

print(f"************ forth rerank, duration:{end - start }\n\n")
```
my error log is 
```
Traceback (most recent call last):
  File "/home/ubuntu/uw-llama/rerank/llm_reanker.py", line 150, in <module>
    new_nodes = get_retrieved_nodes(
  File "/home/ubuntu/uw-llama/rerank/llm_reanker.py", line 109, in get_retrieved_nodes
    retrieved_nodes = reranker.postprocess_nodes(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/postprocessor/types.py", line 55, in postprocess_nodes
    return self._postprocess_nodes(nodes, query_bundle)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/postprocessor/llm_rerank.py", line 99, in _postprocess_nodes
    raw_choices, relevances = self._parse_choice_select_answer_fn(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/indices/utils.py", line 104, in default_parse_choice_select_answer_fn
    answer_num = int(line_tokens[0].split(":")[1].strip())
ValueError: invalid literal for int() with base 10: 'page_label'

```

**Comment by lambda7xx** [comment] 2024-03-27 14:16
the new error is 

```
Traceback (most recent call last):
  File "/home/ubuntu/uw-llama/rerank/llm_reanker.py", line 150, in <module>
    new_nodes = get_retrieved_nodes(
  File "/home/ubuntu/uw-llama/rerank/llm_reanker.py", line 109, in get_retrieved_nodes
    retrieved_nodes = reranker.postprocess_nodes(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/postprocessor/types.py", line 55, in postprocess_nodes
    return self._postprocess_nodes(nodes, query_bundle)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/postprocessor/llm_rerank.py", line 99, in _postprocess_nodes
    raw_choices, relevances = self._parse_choice_select_answer_fn(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/llama_index/core/indices/utils.py", line 104, in default_parse_choice_select_answer_fn
    answer_num = int(line_tokens[0].split(":")[1].strip())
ValueError: invalid literal for int() with base 10: 'page_label'
```

**Comment by logan-markewich** [comment] 2024-03-27 15:57
This is a duplicate of the other issue you opened 👍🏻

**Closed by logan-markewich** 2024-03-27 15:57 UTC
Labels: question
