### ISSUE TITLE
[Bug]: Async parallel data ingestion with multiple workers fails with cache and/or docstore setting

### ISSUE THREAD

**Issue by abratnap** [run-llama/llama_index#14598] opened 2024-07-05 23:10 UTC
### Bug Description

When I try to ingest data using with async pipeline and more than 1 workers
```
await pipeline.arun(show_progress=True, documents=batch, num_workers=2)
```
I get below error.

```
DEBUG:root:Exception running pipeline with batch cannot pickle '_queue.SimpleQueue' object
Exception running pipeline with batch cannot pickle '_queue.SimpleQueue' object
```

I am using Redis as a cache as well as docstore. The error isn't there when I don't set cache and docstore.

```
llma-index version 0.10.52
python version 3.11.8
```

Pipeline is defined as
```
pipeline = IngestionPipeline(
        cache=IngestionCache(
            cache=RedisCache.from_host_and_port(
                os.environ.get(
                    ENV_INGESTION_CACHE_HOST_KEY,
                    DEFAULT_INGESTION_CACHE_HOST_NAME,
                ),
                int(
                    os.environ.get(
                        ENV_INGESTION_CACHE_PORT_KEY,
                        DEFAULT_INGESTION_CACHE_PORT,
                    )
                ),
            ),
            collection=os.environ.get(
                ENV_INGESTION_CACHE_NAME_KEY,
                DEFAULT_INGESTION_CACHE_NAME,
            ),
        ),
        docstore_strategy=DocstoreStrategy.UPSERTS,
        docstore=RedisDocumentStore.from_host_and_port(
            os.environ.get(
                ENV_DOCSTORE_HOST_KEY,
                DEFAULT_DOCSTORE_HOST_NAME,
            ),
            int(
                os.environ.get(
                    ENV_DOCSTORE_PORT_KEY,
                    DEFAULT_DOCSTORE_PORT,
                )
            ),
            namespace=os.environ.get(
                ENV_DOCSTORE_NAMESPACE_KEY,
                DEFAULT_DOCSTORE_NAMESPACE,
            ),
        ),
        transformations=[parser, embeddings_client],
        vector_store=vector_store,
    )
```

### Version

0.10.52

### Steps to Reproduce

Define pipeline with cache and docstore backed by Redis.
Try running async parallel pipeline with multiple workers, as shown in example

**Comment by logan-markewich** [comment] 2024-07-05 23:12
Going to close this is a duplicate of https://github.com/run-llama/llama_index/issues/14572

**Closed by logan-markewich** 2024-07-05 23:12 UTC
Labels: bug, triage
