### ISSUE TITLE
[Bug]: Not able to use GPU with LLama CPP

### ISSUE THREAD

**Issue by kamathis4** [run-llama/llama_index#8105] opened 2023-10-13 05:10 UTC
### Bug Description

Not able to use GPU with Llama CPP with llama index

![Screenshot from 2023-10-13 10-32-05](https://github.com/run-llama/llama_index/assets/11575549/273226bd-f602-4d6d-a523-8b25cbdd7a74)

### Version

0.8.44

### Steps to Reproduce

Tried to use the same with [llama CPP](https://gpt-index.readthedocs.io/en/latest/examples/llm/llama_2_llama_cpp.html)

**Comment by kamathis4** [comment] 2023-10-13 05:56
Tried the exact same code, also installed the llama cpp python library using 

> ! CMAKE_ARGS="-DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS" pip install llama-cpp-python

That according to the docs gives gpu support

**Comment by logan-markewich** [comment] 2023-10-13 15:57
Going to close this -- this is an issue with llama-cpp-python running on google colab, not llamaindex

Maybe this will help -- https://github.com/abetlen/llama-cpp-python/issues/509#issuecomment-1655864538

**Closed by logan-markewich** 2023-10-13 15:57 UTC
Labels: bug, triage

**Comment by mariaKlv** [comment] 2024-04-22 11:21
The problem is still persistent, so I would be grateful if you could re-open it.
