### ISSUE TITLE
[Bug]: Reliability Issue/Version Problems in LlamaIndex

### ISSUE THREAD

**Issue by hherpa** [run-llama/llama_index#16774] opened 2024-11-01 00:55 UTC
### Bug Description

Due to terrible documentation and a severe lack of optimization for developers, which I elaborated on in [LangChain-ToolDocs-Problem](https://github.com/hherpa/LangChain-ToolDocs-Problem), and while waiting for a response to my [issue](https://github.com/langchain-ai/langchain/issues/27668), I had to switch from LangChain to LlamaIndex. However, this immediately presented difficulties: the first three lines of the [documentation](https://llamahub.ai/l/llms/llama-index-llms-fireworks?from=llms)—two lines for installing the library and the line `from llama_index.llms.fireworks import Fireworks`—led me straight to two errors.

In the case of LangChain, the reasons for creating an issue were the need to manually process 98 pages of documentation dedicated to integrating various tools with the LLM agent, as well as API provider platforms (instead of a convenient table like in other sections of the documentation or at least more templated code like in Llama_Index). Here, the problem turned out to be that errors occur "out of the box," literally in the first lines of code after installation.

* I am more interested not so much in solving the specific errors I encountered but in the likelihood of user-side errors occurring in the future. It is expected that by following the documentation instructions, a developer should be able to run the project effortlessly. However, the presence of errors at such an early stage of using the library raises doubts about its stability and reliability.

**Brief Description of the Bug (you can see the full picture in Notebook №1-2):** I am using the latest version of the `llama-Index` and `llama-index-llms-fireworks` libraries, but when I try to access `from llama_index.llms.fireworks import Fireworks`, I encounter two import errors: `cannot import name 'global_handler' from 'llama_index.core' (unknown location)` and `ImportError: cannot import name 'Secret' from 'pydantic'`.

### Version

llama-index 0.11.20 | llama-index-llms-fireworks 0.2.2

### Steps to Reproduce

1. **[Notebook](https://github.com/hherpa/LlamaIndex-Reliability-Issues/blob/main/cannot_import_name_Secret_from_pydantic.ipynb) with the first error**
2. **[Notebook](https://github.com/hherpa/LlamaIndex-Reliability-Issues/blob/main/cannot_import_name_global_handler_from_llama_index.ipynb) with the second error**

**Comment by logan-markewich** [comment] 2024-11-01 01:11
@hherpa This works fine for me (not reproducible)

https://colab.research.google.com/drive/1c-YGjiYrLMg_VFAYbQ9BxFF7RclsGXBU?usp=sharing

I suggest a completely fresh venv, I think something may be corrupted? 

In a fresh terminal, I would run
```
# remove any existing install?
pip freeze | grep llama | xargs pip uninstall -y

# new venv
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-llms-fireworks
```

And then ensure your notebook is using that venv

**Comment by tacacs1101-debug** [comment] 2024-11-01 09:04
llama index has become terrible like langchain. There are so many import issues. I cannot use anthropic & openai llms in the same project due to version conflicts import issues.

**Comment by logan-markewich** [comment] 2024-11-01 14:44
@tacacs1101-debug if you have specific version conflicts, let me know. They install in the same env fine for me

**Comment by hherpa** [comment] 2024-11-01 21:27
> @hherpa This works fine for me (not reproducible)
> 
> https://colab.research.google.com/drive/1c-YGjiYrLMg_VFAYbQ9BxFF7RclsGXBU?usp=sharing
> 
> I suggest a completely fresh venv, I think something may be corrupted?
> 
> In a fresh terminal, I would run
> 
> ```
> # remove any existing install?
> pip freeze | grep llama | xargs pip uninstall -y
> 
> # new venv
> python -m venv venv
> source venv/bin/activate
> pip install llama-index llama-index-llms-fireworks
> ```
> 
> And then ensure your notebook is using that venv

Reinstalling libraries and restarting the venv did not help resolve the error. Here is my [notebook](https://github.com/hherpa/LlamaIndex-Reliability-Issues/blob/main/global_handler_from_llama_index_core_2.ipynb) with the reproduction. @logan-markewich 
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[20], line 3
      1 from llama_index.llms.fireworks import Fireworks
----> 3 llm = Fireworks(
      4     model="accounts/fireworks/models/firefunction-v1", api_key="YOUR_API_KEY"
      5 )
      6 resp = llm.complete("Paul Graham is ")
      7 print(resp)

File ~\AppData\Roaming\Python\Python311\site-packages\llama_index\llms\fireworks\base.py:57, in Fireworks.__init__(self, model, temperature, max_tokens, additional_kwargs, max_retries, api_base, api_key, callback_manager, default_headers, system_prompt, messages_to_prompt, completion_to_prompt, pydantic_program_mode, output_parser)
     39 def __init__(
     40     self,
     41     model: str = DEFAULT_MODEL,
   (...)
     54     output_parser: Optional[BaseOutputParser] = None,
     55 ) -> None:
     56     additional_kwargs = additional_kwargs or {}
---> 57     callback_manager = callback_manager or CallbackManager([])
     59     api_base = get_from_param_or_env("api_base", api_base, "FIREWORKS_API_BASE")
     60     api_key = get_from_param_or_env("api_key", api_key, "FIREWORKS_API_KEY")

File ~\AppData\Roaming\Python\Python311\site-packages\llama_index\core\callbacks\base.py:59, in CallbackManager.__init__(self, handlers)
     57 def __init__(self, handlers: Optional[List[BaseCallbackHandler]] = None):
     58     """Initialize the manager with a list of handlers."""
---> 59     from llama_index.core import global_handler
     61     handlers = handlers or []
     63     # add eval handlers based on global defaults

ImportError: cannot import name 'global_handler' from 'llama_index.core' (unknown location)
```

**Comment by logan-markewich** [comment] 2024-11-02 16:12
Are you sure your API key was there? 

Following the code
https://github.com/run-llama/llama_index/blob/f278bafbd5c03bbcb4c64afa2e56620c4dce631e/llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/base.py#L60

Which calls
https://github.com/run-llama/llama_index/blob/f278bafbd5c03bbcb4c64afa2e56620c4dce631e/llama-index-core/llama_index/core/base/llms/generic_utils.py#L297

Which if `api_key` was passed in, would end up returning here
https://github.com/run-llama/llama_index/blob/f278bafbd5c03bbcb4c64afa2e56620c4dce631e/llama-index-core/llama_index/core/base/llms/generic_utils.py#L305

The only way that error gets raised is if `api_key=None` and `FIREWORKS_API_KEY` is not in your env

Using the same notebook above, you can see that the same error is never raised using your code. I also modified it to call that `get_from_param_or_env` method directly to show that it also works
https://colab.research.google.com/drive/1c-YGjiYrLMg_VFAYbQ9BxFF7RclsGXBU?usp=sharing

I think maybe make sure you restart your notebook

**Comment by logan-markewich** [comment] 2024-11-02 16:12
(cc @hherpa )

**Comment by hherpa** [comment] 2024-11-02 17:09
@logan-markewich I tried restarting Jupyter and reinstalling it, but the error still persists. I’m certain I provided my API key correctly — it was placed instead of the string `"My API key was here"`. I don’t understand why `llama_index` thinks I'm passing `None`, as even in the example, you can see in line 4 of the code that I set the `api_key` variable with the value `"My API key was here"`.

**Comment by logan-markewich** [comment] 2024-11-02 17:45
@hherpa I'm not really sure either. If you can reproduce in Google colab (i couldnt), happy to help debug more, but if I can't reproduce, it's a little hard to help 🤔

If you are comfortable using debugger, feel free to step through the constructor code and see what's going on on your end

**Comment by logan-markewich** [comment] 2024-11-02 18:26
@hherpa I'm see the issue in your code

You are doing `resp = Firworks().complete(..)` -- no api key is passed because you are reinsansiating the llm object with no api key or model name

**Comment by logan-markewich** [comment] 2024-11-02 18:27
The correct code would be

```
from llama_index.llms.fireworks import Fireworks

llm = Fireworks(
    model="accounts/fireworks/models/firefunction-v1", api_key="My api key was here"
)
resp = llm.complete("Paul Graham is ")
print(resp)
```

**Comment by hherpa** [comment] 2024-11-02 18:50
@logan-markewich  Yes, you are absolutely correct – this fixed the error and led to successful generation. However, the main issue now is that this code is from the primary [documentation](https://docs.llamaindex.ai/en/stable/examples/llm/fireworks/).

![image](https://github.com/user-attachments/assets/ded42b04-f3d9-4d0b-968a-efc6c6c28e39)

Interestingly, in the [documentation](https://llamahub.ai/l/llms/llama-index-llms-fireworks?from=llms) for Llamahub, the code is written correctly:

![image](https://github.com/user-attachments/assets/41208f48-849f-462a-9f34-adf1150c32bb)

**Comment by logan-markewich** [comment] 2024-11-02 19:54
Fair. I have a PR open for this (see the link below)

**Comment by logan-markewich** [comment] 2024-11-02 20:34
Closing this issue out with that.

If you run into anything else, I'm usually monitoring new issues and our discord pretty closely.

Cheers!

**Closed** 2024-11-02 20:34 UTC
Labels: bug, triage
