### ISSUE TITLE
[Bug]:  Issue with pip install llama-index

### ISSUE THREAD

**Issue by kindler-king** [run-llama/llama_index#9943] opened 2024-01-09 21:42 UTC
### Bug Description

I tried installing llama_index on both Google Colab and my local machine and I am met with this wierd (but same) error.

`Collecting llama-index
  Using cached llama_index-0.9.28.post1-py3-none-any.whl (15.8 MB)
Requirement already satisfied: SQLAlchemy[asyncio]>=1.4.49 in /usr/local/lib/python3.10/dist-packages (from llama-index) (2.0.24)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.10/dist-packages (from llama-index) (3.9.1)
Collecting beautifulsoup4<5.0.0,>=4.12.2 (from llama-index)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting dataclasses-json (from llama-index)
  Using cached dataclasses_json-0.6.3-py3-none-any.whl (28 kB)
Collecting deprecated>=1.2.9.3 (from llama-index)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from llama-index) (2023.6.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from llama-index) (0.26.0)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.10/dist-packages (from llama-index) (1.5.8)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.10/dist-packages (from llama-index) (3.2.1)
Requirement already satisfied: nltk<4.0.0,>=3.8.1 in /usr/local/lib/python3.10/dist-packages (from llama-index) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from llama-index) (1.23.5)
Requirement already satisfied: openai>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from llama-index) (1.7.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from llama-index) (1.5.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from llama-index) (2.31.0)
Requirement already satisfied: tenacity<9.0.0,>=8.2.0 in /usr/local/lib/python3.10/dist-packages (from llama-index) (8.2.3)
Collecting tensorrt_llm<0.8.0,>=0.7.1 (from llama-index)
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I have pasted the logs here for reference. I have never encountered this any suggestions about whats going on?
Does it have something to do with the latest release?
![image](https://github.com/run-llama/llama_index/assets/53633591/580bc3a8-972f-49c2-ad2b-d2b1cc4d39ac)

### Version

llama-index 0.9.28.post1

### Steps to Reproduce

pip install llama-index in terminal

**Comment by hatianzhang** [comment] 2024-01-09 22:53
cannot reproduce ```Installing collected packages: llama-index
Successfully installed llama-index-0.9.28.post1
```

**Comment by aishwaryaprabhat** [comment] 2024-01-09 23:36
Faced the same issue on Google Colab. 0.9.27 seems to be fine

![Uploading Screenshot 2024-01-10 at 7.33.55 AM.png…]()

**Comment by logan-markewich** [comment] 2024-01-10 00:01
Should be fixed here
https://github.com/run-llama/llama_index/pull/9946

Well put out a new release asap

**Closed** 2024-01-10 00:03 UTC
Labels: bug, triage

**Comment by aishwaryaprabhat** [comment] 2024-01-10 00:07
Thank you for the quick fix @logan-markewich!
