### ISSUE TITLE
[Question]: Merge vectore index

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#8883] opened 2023-11-13 06:51 UTC
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I have two documents, and each document has a vector index built, how can I merge the two vector indexes together?

**Comment by logan-markewich** [comment] 2023-11-13 15:44
This is a duplicate of https://github.com/run-llama/llama_index/issues/8885

**Closed by logan-markewich** 2023-11-13 15:44 UTC
Labels: question

**Comment by Aniketparab1999** [comment] 2024-03-11 10:41
index1 = GPTVectorStoreIndex(nodes = doc1, service_context=service_context, storage_context=storage_context,show_progress=True)
index2 = GPTVectorStoreIndex(nodes = doc2, service_context=service_context, storage_context=storage_context,show_progress=True)

I have this type of different indices for different document (For Llamaindex framework)
How can I combine these indices
I tried GPTListIndex which is not working

**Comment by Aniketparab1999** [comment] 2024-03-11 10:45
Also How can I use Cohere reranking in Sub question Query Engine for Llamaindex
Because while dealing with large number of documents in llamaindex with Sub question query engine
It is giving rate limit error since it is searching from each and every document
