### ISSUE TITLE
[Question]: Analyze a image with GPT4 Vision?

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#12978] opened 2024-04-20 17:21 UTC
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I seem to remember being able to use SimpleDirectoryReader to describe images as tags just fine, until now. Now I see this whole quite elaborate MultiModal thing just to analyze and image when GPT-4 Vision is already setup to accept a image buffer to take a look at. What happened? 

Similarly, I was able to use GPT4 Vision with videos and audio with SimpleDirectoryReader and it was a quite easy process, but now I see very drawn out multimodal setups and deps

**Comment by logan-markewich** [comment] 2024-04-20 17:33
You can still give an image to gpt4

https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal/

Here's a fun one
https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pydantic/?h=multimodal

**Comment by WAS-PlaiLabs** [comment] 2024-04-20 17:38
> You can still give an image to gpt4
> 
> https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal/
> 
> Here's a fun one https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pydantic/?h=multimodal

The issue I'm facing is this breaks the entire paradigm of our node structure, where now we can't use service_context with multimodals because of an error about no callback function or something -- So we can't even use Multimodal with our existing setups and have to rewrite the entire base. But service_context is a foundational part of how we get the right models context to the right nodes within our system.

It seems important to go through deprecation periods where we have legacy support and enough time to implement changes instead of the whole system becoming broken one update to another. There doesn't seem to be any indication on the github page that this is an unstable alpha project when installing through pip.

**Comment by logan-markewich** [comment] 2024-04-20 18:48
The callback thing is a bug, it should be fixed.

Service context is deprecated but still fully supported for the coming months

**Comment by WAS-PlaiLabs** [comment] 2024-04-20 18:52
What is the replacement for passing a specific model to vector indexes and everything else if service_context is deprecated? We use multiple models at once and need clear separation of flows.

**Comment by logan-markewich** [comment] 2024-04-20 18:56
You pass in models to where they are used 

VectorStoreIndex(..., embed_model=embed_model)


index.as_query_engine(..., llm=llm)


Every api that uses an embed model or llm accepts it in the api. You can also change the global defaults. This is detailed here
https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/service_context_migration/?h=settings

https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/settings/?h=settings

**Comment by logan-markewich** [comment] 2024-04-20 18:58
It's very explicit now what objects and classes use which models.

For example, you don't need to initialize an llm to build a vector index

**Comment by WAS-PlaiLabs** [comment] 2024-04-20 19:09
Another question, wrapping back to callback error, when will that fix be released on the pip packages? I seem to up to date on all packages but still get the callback error with openai multimodal.

**Comment by logan-markewich** [comment] 2024-04-21 01:44
Its not fixed. I know what the issue is. Just need to make time to fix it (or you or someone else could make the PR)

But, it's also the weekend and I'm mostly AFK for now

**Comment by WAS-PlaiLabs** [comment] 2024-04-29 20:39
Did this patch slip in somewhere? Sorry, I've been trying to monitor the commits but may have missed it.

**Comment by WAS-PlaiLabs** [comment] 2024-05-13 21:24
I still get the same error about no callback manager field when I use MultiModal with query engine: `"OpenAIMultiModal" object has no field "callback_manager"` I see there is a param for callback manager on the OpenAIMultiModel, does that need to be explicitly set with a callback manager?

**Closed** 2024-08-19 16:10 UTC
Labels: question
