### ISSUE TITLE
[Bug]: No module named 'openai.openai_object'

### ISSUE THREAD

**Issue by hynky1999** [run-llama/llama_index#9292] opened 2023-12-04 10:42 UTC
### Bug Description

After clean installing the llama-index, I am getting following error:
`No module named 'openai.openai_object'`

when running almost anything from llama-index e.g:
```
from llama_index import download_loader
import os

AirtableReader = download_loader('AirtableReader')

reader = AirtableReader(AIRTABLE_API_KEY)
```

I believe this is caused by the breaking changes in openai>1.x.x of `openai` package.

### Version

0.8.42

### Steps to Reproduce

Clean install `llama-index` on python3.12

Run following code:
```
from llama_index import download_loader
import os

AirtableReader = download_loader('AirtableReader')

reader = AirtableReader("TEST")
```

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/Users/hynekkdylicek/airtable/fun.ipynb Cell 5 line 1
----> 1 from llama_index import download_loader
      2 import os
      4 AirtableReader = download_loader('AirtableReader')

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/__init__.py:21
     18 from llama_index.embeddings.openai import OpenAIEmbedding
     20 # structured
---> 21 from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
     23 # for composability
     24 from llama_index.indices.composability.graph import ComposableGraph

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/__init__.py:4
      1 """LlamaIndex data structures."""
      3 # indices
----> 4 from llama_index.indices.document_summary.base import DocumentSummaryIndex
      5 from llama_index.indices.keyword_table.base import (
      6     GPTKeywordTableIndex,
      7     KeywordTableIndex,
      8 )
      9 from llama_index.indices.keyword_table.rake_base import (
     10     GPTRAKEKeywordTableIndex,
     11     RAKEKeywordTableIndex,
     12 )

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/document_summary/__init__.py:4
      1 """Document summary index."""
----> 4 from llama_index.indices.document_summary.base import (
      5     DocumentSummaryIndex,
      6     GPTDocumentSummaryIndex,
      7 )
      8 from llama_index.indices.document_summary.retrievers import (
      9     DocumentSummaryIndexEmbeddingRetriever,
     10     DocumentSummaryIndexLLMRetriever,
     11     DocumentSummaryIndexRetriever,
     12 )
     14 __all__ = [
     15     "DocumentSummaryIndex",
     16     "DocumentSummaryIndexLLMRetriever",
   (...)
     20     "DocumentSummaryIndexRetriever",
     21 ]

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/document_summary/base.py:14
     11 from typing import Any, Dict, Optional, Sequence, Union, cast
     13 from llama_index.data_structs.document_summary import IndexDocumentSummary
---> 14 from llama_index.indices.base import BaseIndex
     15 from llama_index.indices.base_retriever import BaseRetriever
     16 from llama_index.indices.service_context import ServiceContext

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/base.py:6
      3 from abc import ABC, abstractmethod
      4 from typing import Any, Dict, Generic, List, Optional, Sequence, Type, TypeVar, cast
----> 6 from llama_index.chat_engine.types import BaseChatEngine, ChatMode
      7 from llama_index.data_structs.data_structs import IndexStruct
      8 from llama_index.indices.base_retriever import BaseRetriever

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/chat_engine/__init__.py:1
----> 1 from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
      2 from llama_index.chat_engine.context import ContextChatEngine
      3 from llama_index.chat_engine.simple import SimpleChatEngine

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/chat_engine/condense_question.py:6
      3 from typing import Any, List, Optional, Type
      5 from llama_index.callbacks import CallbackManager, trace_method
----> 6 from llama_index.chat_engine.types import (
      7     AgentChatResponse,
      8     BaseChatEngine,
      9     StreamingAgentChatResponse,
     10 )
     11 from llama_index.chat_engine.utils import response_gen_from_query_engine
     12 from llama_index.indices.query.base import BaseQueryEngine

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/chat_engine/types.py:14
     12 from llama_index.response.schema import Response, StreamingResponse
     13 from llama_index.schema import NodeWithScore
---> 14 from llama_index.tools import ToolOutput
     16 logger = logging.getLogger(__name__)
     17 logger.setLevel(logging.WARNING)

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/tools/__init__.py:5
      3 from llama_index.tools.function_tool import FunctionTool
      4 from llama_index.tools.query_engine import QueryEngineTool
----> 5 from llama_index.tools.query_plan import QueryPlanTool
      6 from llama_index.tools.retriever_tool import RetrieverTool
      7 from llama_index.tools.types import (
      8     AsyncBaseTool,
      9     BaseTool,
   (...)
     12     adapt_to_async_tool,
     13 )

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/tools/query_plan.py:6
      3 from typing import Any, Dict, List, Optional
      5 from llama_index.bridge.pydantic import BaseModel, Field
----> 6 from llama_index.response_synthesizers import BaseSynthesizer, get_response_synthesizer
      7 from llama_index.schema import NodeWithScore, TextNode
      8 from llama_index.tools.types import BaseTool, ToolMetadata, ToolOutput

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/response_synthesizers/__init__.py:3
      1 """Init file."""
----> 3 from llama_index.response_synthesizers.accumulate import Accumulate
      4 from llama_index.response_synthesizers.base import BaseSynthesizer
      5 from llama_index.response_synthesizers.compact_and_refine import CompactAndRefine

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/response_synthesizers/accumulate.py:5
      2 from typing import Any, List, Optional, Sequence
      4 from llama_index.async_utils import run_async_tasks
----> 5 from llama_index.indices.service_context import ServiceContext
      6 from llama_index.prompts import BasePromptTemplate
      7 from llama_index.prompts.default_prompts import DEFAULT_TEXT_QA_PROMPT

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/service_context.py:10
      8 from llama_index.embeddings.base import BaseEmbedding
      9 from llama_index.embeddings.utils import EmbedType, resolve_embed_model
---> 10 from llama_index.indices.prompt_helper import PromptHelper
     11 from llama_index.llm_predictor import LLMPredictor
     12 from llama_index.llm_predictor.base import BaseLLMPredictor, LLMMetadata

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/indices/prompt_helper.py:16
     14 from llama_index.bridge.pydantic import Field, PrivateAttr
     15 from llama_index.constants import DEFAULT_CONTEXT_WINDOW, DEFAULT_NUM_OUTPUTS
---> 16 from llama_index.llm_predictor.base import LLMMetadata
     17 from llama_index.llms.openai_utils import is_chat_model
     18 from llama_index.prompts import BasePromptTemplate

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/llm_predictor/__init__.py:3
      1 """Init params."""
----> 3 from llama_index.llm_predictor.base import LLMPredictor
      5 # NOTE: this results in a circular import
      6 # from llama_index.llm_predictor.mock import MockLLMPredictor
      7 from llama_index.llm_predictor.structured import StructuredLLMPredictor

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/llm_predictor/base.py:18
     11 from llama_index.llm_predictor.utils import (
     12     astream_chat_response_to_tokens,
     13     astream_completion_response_to_tokens,
     14     stream_chat_response_to_tokens,
     15     stream_completion_response_to_tokens,
     16 )
     17 from llama_index.llms.base import LLM, ChatMessage, LLMMetadata, MessageRole
---> 18 from llama_index.llms.utils import LLMType, resolve_llm
     19 from llama_index.prompts.base import BasePromptTemplate, PromptTemplate
     20 from llama_index.schema import BaseComponent

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/llms/__init__.py:23
     21 from llama_index.llms.konko import Konko
     22 from llama_index.llms.langchain import LangChainLLM
---> 23 from llama_index.llms.litellm import LiteLLM
     24 from llama_index.llms.llama_cpp import LlamaCPP
     25 from llama_index.llms.localai import LocalAI

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/llms/litellm.py:28
      5 from llama_index.llms.base import (
      6     LLM,
      7     ChatMessage,
   (...)
     16     llm_completion_callback,
     17 )
     18 from llama_index.llms.generic_utils import (
     19     achat_to_completion_decorator,
     20     acompletion_to_chat_decorator,
   (...)
     26     stream_completion_to_chat_decorator,
     27 )
---> 28 from llama_index.llms.litellm_utils import (
     29     acompletion_with_retry,
     30     completion_with_retry,
     31     from_openai_message_dict,
     32     is_chat_model,
     33     is_function_calling_model,
     34     openai_modelname_to_contextsize,
     35     to_openai_message_dicts,
     36     validate_litellm_api_key,
     37 )
     40 class LiteLLM(LLM):
     41     model: str = Field(
     42         description="The LiteLLM model to use."
     43     )  # For complete list of providers https://docs.litellm.ai/docs/providers

File ~/.pyenv/versions/3.12.0/envs/airtable3.12/lib/python3.12/site-packages/llama_index/llms/litellm_utils.py:4
      1 import logging
      2 from typing import Any, Callable, Dict, List, Optional, Sequence, Type
----> 4 from openai.openai_object import OpenAIObject
      5 from tenacity import (
      6     before_sleep_log,
      7     retry,
   (...)
     10     wait_exponential,
     11 )
     13 from llama_index.bridge.pydantic import BaseModel

ModuleNotFoundError: No module named 'openai.openai_object'
```

**Comment by hynky1999** [comment] 2023-12-04 20:37
Frankly I have no idea why you close it without waiting for the response for at least 24hours.
Here is why the problem occured:
The highest version of llama-index supported for python3.12 is `0.8.42`.
Trying to anywhere higher results in:

```
ERROR: Ignored the following versions that require a different python version: 0.8.43 Requires-Python >=3.8.1,<3.12; 0.8.43.post1 Requires-Python >=3.8.1,<3.12; 0.8.44 Requires-Python >=3.8.1,<3.12; 0.8.45 Requires-Python >=3.8.1,<3.12; 0.8.45.post1 Requires-Python >=3.8.1,<3.12; 0.8.46 Requires-Python >=3.8.1,<3.12; 0.8.47 Requires-Python >=3.8.1,<3.12; 0.8.48 Requires-Python >=3.8.1,<3.12; 0.8.49 Requires-Python >=3.8.1,<3.12; 0.8.50 Requires-Python >=3.8.1,<3.12; 0.8.51 Requires-Python >=3.8.1,<3.12; 0.8.51.post1 Requires-Python >=3.8.1,<3.12; 0.8.52 Requires-Python >=3.8.1,<3.12; 0.8.53 Requires-Python >=3.8.1,<3.12; 0.8.53.post3 Requires-Python >=3.8.1,<3.12; 0.8.54 Requires-Python >=3.8.1,<3.12; 0.8.55 Requires-Python >=3.8.1,<3.12; 0.8.56 Requires-Python >=3.8.1,<3.12; 0.8.57 Requires-Python >=3.8.1,<3.12; 0.8.58 Requires-Python >=3.8.1,<3.12; 0.8.59 Requires-Python >=3.8.1,<3.12; 0.8.61 Requires-Python >=3.8.1,<3.12; 0.8.62 Requires-Python >=3.8.1,<3.12; 0.8.63.post1 Requires-Python >=3.8.1,<3.12; 0.8.63.post2 Requires-Python >=3.8.1,<3.12; 0.8.64 Requires-Python >=3.8.1,<3.12; 0.8.64.post1 Requires-Python >=3.8.1,<3.12; 0.8.65 Requires-Python >=3.8.1,<3.12; 0.8.66 Requires-Python >=3.8.1,<3.12; 0.8.67 Requires-Python >=3.8.1,<3.12; 0.8.68 Requires-Python >=3.8.1,<3.12; 0.8.69 Requires-Python >=3.8.1,<3.12; 0.8.69.post1 Requires-Python >=3.8.1,<3.12; 0.8.69.post2 Requires-Python >=3.8.1,<3.12; 0.9.0 Requires-Python >=3.8.1,<3.12; 0.9.0.post1 Requires-Python >=3.8.1,<3.12; 0.9.0a1 Requires-Python >=3.8.1,<3.12; 0.9.0a2 Requires-Python >=3.8.1,<3.12; 0.9.0a3 Requires-Python >=3.8.1,<3.12; 0.9.1 Requires-Python >=3.8.1,<3.12; 0.9.10 Requires-Python >=3.8.1,<3.12; 0.9.10a1 Requires-Python >=3.8.1,<3.12; 0.9.10a2 Requires-Python >=3.8.1,<3.12; 0.9.11 Requires-Python >=3.8.1,<3.12; 0.9.11.post1 Requires-Python >=3.8.1,<3.12; 0.9.2 Requires-Python >=3.8.1,<3.12; 0.9.3 Requires-Python >=3.8.1,<3.12; 0.9.3.post1 Requires-Python >=3.8.1,<3.12; 0.9.4 Requires-Python >=3.8.1,<3.12; 0.9.5 Requires-Python >=3.8.1,<3.12; 0.9.6 Requires-Python >=3.8.1,<3.12; 0.9.6.post1 Requires-Python >=3.8.1,<3.12; 0.9.6.post2 Requires-Python >=3.8.1,<3.12; 0.9.7 Requires-Python >=3.8.1,<3.12; 0.9.8 Requires-Python >=3.8.1,<3.12; 0.9.8.post1 Requires-Python >=3.8.1,<3.12; 0.9.9 Requires-Python >=3.8.1,<3.12
ERROR: Could not find a version that satisfies the requirement llama-index==0.9.11 (from versions: 0.4.4, 0.4.4.post1, 0.4.4.post2, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.22.post1, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.4.35, 0.4.35.post1, 0.4.36, 0.4.37, 0.4.38, 0.4.39, 0.4.40, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.5.11, 0.5.12, 0.5.13, 0.5.13.post1, 0.5.15, 0.5.16, 0.5.17, 0.5.17.post1, 0.5.18, 0.5.19, 0.5.20, 0.5.21, 0.5.22, 0.5.23, 0.5.23.post1, 0.5.25, 0.5.26, 0.5.27, 0.6.0a1, 0.6.0a2, 0.6.0a3, 0.6.0a4, 0.6.0a5, 0.6.0a6, 0.6.0a7, 0.6.0, 0.6.1, 0.6.2, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.10.post1, 0.6.11, 0.6.12, 0.6.13, 0.6.14, 0.6.15, 0.6.16, 0.6.16.post1, 0.6.17, 0.6.18, 0.6.19, 0.6.20, 0.6.21.post1, 0.6.22, 0.6.23, 0.6.24, 0.6.25, 0.6.25.post1, 0.6.26, 0.6.27, 0.6.28, 0.6.29, 0.6.30, 0.6.31, 0.6.32, 0.6.33, 0.6.34, 0.6.34.post1, 0.6.35, 0.6.36, 0.6.37, 0.6.38, 0.6.38.post1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.10.post1, 0.7.11, 0.7.11.post1, 0.7.12, 0.7.13, 0.7.14, 0.7.15, 0.7.16, 0.7.17, 0.7.18, 0.7.19, 0.7.20, 0.7.21, 0.7.22, 0.7.23, 0.7.24.post1, 0.8.0, 0.8.1, 0.8.1.post1, 0.8.2, 0.8.2.post1, 0.8.3, 0.8.4, 0.8.5, 0.8.5.post1, 0.8.5.post2, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 0.8.10.post1, 0.8.11, 0.8.11.post1, 0.8.11.post2, 0.8.11.post3, 0.8.12, 0.8.13, 0.8.14, 0.8.15, 0.8.16, 0.8.17, 0.8.18, 0.8.19, 0.8.20, 0.8.21, 0.8.22, 0.8.23, 0.8.23.post1, 0.8.24, 0.8.24.post1, 0.8.25, 0.8.26, 0.8.26.post1, 0.8.27, 0.8.28a1, 0.8.28, 0.8.29, 0.8.29.post1, 0.8.30, 0.8.31, 0.8.32, 0.8.33, 0.8.34, 0.8.35, 0.8.36, 0.8.37, 0.8.38, 0.8.39, 0.8.39.post2, 0.8.40, 0.8.41, 0.8.42)
ERROR: No matching distribution found for llama-index==0.9.11
```

I think this is valid issue, which is certainly not resolved.

**Comment by logan-markewich** [comment] 2023-12-05 00:19
Python 3.12 isn't technically supported yet. 

The requirement was specifically added after python3.12 released, which is why it looks like newer versions don't support it

Please downgrade, but we should have support added at some point

**Comment by logan-markewich** [comment] 2023-12-05 00:35
Related issue: https://github.com/run-llama/llama_index/issues/8153

**Comment by logan-markewich** [comment] 2023-12-05 01:38
Merged python 3.12 support. Will be released with v0.9.12 in the next little but

**Closed** 2023-12-05 01:38 UTC
Labels: bug, triage

**Comment by hynky1999** [comment] 2023-12-05 23:00
Awesome, thanks for the fix

**Comment by alecthekulak** [comment] 2024-02-14 20:50
I'm seeing `ModuleNotFoundError: No module named 'openai.openai_object'` even with Python version 3.11.5, so this issue does not appear to be restricted to Python 3.12

![image](https://github.com/marklysze/LlamaIndex-RAG-WSL-CUDA/assets/5726079/6776ad8b-64fe-4dfc-9a75-7ac8dfa59c61)

**Comment by logan-markewich** [comment] 2024-02-14 21:14
@alecthekulak what version of openai do you have? I would just reinstall from a fresh venv tbh

**Comment by alecthekulak** [comment] 2024-02-14 21:57
I specify 1.12.0 in my Conda environment but when I import it I only see 1.9.0

**Comment by cohml** [comment] 2024-03-15 16:44
Reproduced on Python 3.12 with the latest `openai`:

```shell
❯ conda list openai -p ./env
# packages in environment at /Users/[redacted]/env:
#
# Name                    Version                   Build  Channel
openai                    1.14.0             pyhd8ed1ab_0    /
❯ ./env/bin/python --version
Python 3.12.2
❯ ./env/bin/python -c "import openai.openai_object"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'openai.openai_object'```

**Comment by MighettoWasTaken** [comment] 2024-08-19 20:43
Occurring on 3.11.9 
![Screenshot 2024-08-19 134155](https://github.com/user-attachments/assets/505889e6-9663-4fd0-8a81-77d43f12bffa)

I also noticed this message in the ouput: 
``` : Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatAnyscale`. ``` 

Perhaps this has to do with the issue?
