### ISSUE TITLE
[Bug]: SimpleDirectoryReader not encoding text correctly

### ISSUE THREAD

**Issue by chowgi** [run-llama/llama_index#10683] opened 2024-02-14 03:37 UTC
### Bug Description

![Screenshot 2024-02-14 at 2 12 44 PM](https://github.com/run-llama/llama_index/assets/6829811/4142cb92-dfde-48bf-8380-4fbc8b42d94a)

When loading a pdf this is the sort of text that is being vectorized. I have tried multiple PDF's and .docx with the same result.

### Version

0.10.3

### Steps to Reproduce

Load a pdf using SimpleDirectoryReader and query eg.

documents = SimpleDirectoryReader(input-dir="./data").load_data()
index = VectorStoreIndex.from_documents(documents)
response = index.as_query_engine().query("Provide a summary for the context?")
print(f"<b>{response}</b>")

Code works fine with .txt files

**Comment by logan-markewich** [comment] 2024-02-14 03:50
@chowgi this should be fixed in the latest v0.10.3, I cannot reproduce 👁️

**Comment by logan-markewich** [comment] 2024-02-14 04:00
https://colab.research.google.com/drive/1kUgT_KZpCiHQXVUBFSnjqjioJQ9P6hpt?usp=sharing

Make sure you run `pip install -U llama-index llama-index-core`

**Comment by chowgi** [comment] 2024-02-14 08:18
Yeah okay. I thought I had upgraded to 0.10.3 but I may have only done llama-index and not llama-index-core. I have now upgraded and it's working. Appreciate the speedy response!

**Closed** 2024-02-14 13:52 UTC
Labels: bug, triage
