### ISSUE TITLE
[Bug]: ValidationError: 1 validation error for NodeWithScore node   Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)

### ISSUE THREAD

**Issue by ayseozgun** [run-llama/llama_index#10706] opened 2024-02-14 14:05 UTC
### Bug Description

Hi,

I am trying to run a query by using chat engine. My vector store is in pinecone. My code was running properly with version 9. But i wanted to adjust my codes for version 10. can you please help me? What can be wrong?

Thanks in advance,

### Version

0.10.3

### Steps to Reproduce

index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
engine = index.as_chat_engine(similarity_top_k= 10,
    chat_mode="condense_plus_context",
    llm=llm,
    context_prompt=context_prompt,
    verbose=False,
)
engine.chat(question)

**Comment by ayseozgun** [comment] 2024-02-14 14:23
I am using sentence window method. I have only nodes.
`from llama_index.core.node_parser.text.sentence_window import SentenceWindowNodeParser
from llama_index.core.node_parser import SentenceSplitter

# create the sentence window node parser w/ default settings
node_parser = SentenceWindowNodeParser.from_defaults(
    window_size=5,
    window_metadata_key="window",
    original_text_metadata_key="original_text",
)
nodes = node_parser.build_window_nodes_from_documents(docs)`

I inserted nodes to the vector store.

**Comment by nerdai** [comment] 2024-02-14 17:37
https://github.com/run-llama/llama_index/issues/10697#issuecomment-1944228353

@ayseozgun not sure if you saw my response in the other (perhaps related) issue. With a fresh venv, I was able to create a VectorStoreIndex from a VectorStore (namely qdrant) and use it successfully as a query engine.

Please do ensure that you are using a brand new virtual env when working with v0.10.

**Comment by ayseozgun** [comment] 2024-02-15 18:14
Thanks for response.

I tried in new env with these versions, still did not work and same error:

`llama-index                         0.10.3
llama-index-agent-openai            0.1.1
llama-index-core                    0.10.3
llama-index-embeddings-openai       0.1.1
llama-index-legacy                  0.9.48
llama-index-llms-anyscale           0.1.1
llama-index-llms-langchain          0.1.1
llama-index-llms-openai             0.1.1
llama-index-multi-modal-llms-openai 0.1.1
llama-index-program-openai          0.1.1
llama-index-question-gen-openai     0.1.1
llama-index-readers-file            0.1.3`

**Comment by nerdai** [comment] 2024-02-15 19:09
> Thanks for response.
> 
> I tried in new env with these versions, still did not work and same error:
> 
> `llama-index 0.10.3 llama-index-agent-openai 0.1.1 llama-index-core 0.10.3 llama-index-embeddings-openai 0.1.1 llama-index-legacy 0.9.48 llama-index-llms-anyscale 0.1.1 llama-index-llms-langchain 0.1.1 llama-index-llms-openai 0.1.1 llama-index-multi-modal-llms-openai 0.1.1 llama-index-program-openai 0.1.1 llama-index-question-gen-openai 0.1.1 llama-index-readers-file 0.1.3`

Thanks for confirming. Will find some time to replicate the issue on my end with your setup:

- pinecone vector store
- openai llms/embeddings

Correct?

**Comment by nerdai** [comment] 2024-02-16 03:11
@ayseozgun I'm going to mark thiat as duplicate of #10697 and close this issue in favour of having comms in that one instead.

**Closed by nerdai** 2024-02-16 03:11 UTC
Labels: bug, v0.10.X
