### ISSUE TITLE
[Bug]: VectorStoreIndex.refresh_ref_docs() duplicate docs with PGVectorStore

### ISSUE THREAD

**Issue by 3chospirits** [run-llama/llama_index#8832] opened 2023-11-10 09:30 UTC
### Bug Description

`VectorStoreIndex.refresh_ref_docs()` inserts every time instead of the expected upsert behavior when using PGVectorStore as vector store

### Version

0.8.66

### Steps to Reproduce

Here are snippets of my code:
```py
from llama_index.vector_stores import PGVectorStore
from llama_index.indices.vector_store import VectorStoreIndex

confluence_vector_store = PGVectorStore.from_params(
    database=os.environ.get("DB_DATABASE"),
    host=os.environ.get("DB_HOST"),
    password=os.environ.get("DB_PASSWORD"),
    port=os.environ.get("DB_PORT"),
    user=os.environ.get("DB_USER"),
    table_name="confluence",
    embed_dim=1536
)

confluence_index = VectorStoreIndex.from_vector_store(
    vector_store=confluence_vector_store, delete_from_docstore=True)

docs = Document(
        text="This isn't in the index yet, but it will be soon!",
        id_="doc_id_3",
    )

confluence_index.refresh_ref_docs(docs, update_kwargs={"delete_kwargs": {"delete_from_docstore": True}})


# Additional Debugging code I tried to run to locate the problem. It seems like the data isn't being added to the datastore at all, which is why the get_document_hash() function in refresh_ref_docs() is returning null. 
# print(confluence_index._storage_context.docstore._kvstore.get_all())
# ^ this ends up returning an empty kvstore even when the vector storage is populated.
```

Running the same code twice SHOULD have it only insert the document once into the document, with the second one doing nothing since the document is already there. Hoewver, it ends up being inserted twice.

**Comment by logan-markewich** [comment] 2023-11-10 15:46
@3chospirits the docstore (which is used to track uploaded documents) isn't used by default when using a 3rd party vector db

This is because the entire index ends up getting stored in the vector db. This simplifies storage a lot, at the cost of this feature not working by default.

If you want, you can override this, but then you need to manage a docstore object and it's storage

Here's an example I had floating around that uses chroma, but PostgreSQL will be similar 

```python
from llama_index import VectorStoreIndex, StorageContext, Document
from llama_index.vector_stores import ChromaVectorStore

import chromadb
db = chromadb.PersistentClient(path="./chroma_db")
chroma_collection = db.get_or_create_collection("quickstart")
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

documents = [Document(text="document 1", doc_id="doc1")]

# test and confirm single document is retrieved
index = VectorStoreIndex.from_documents(documents, storage_context=storage_context, store_nodes_override=True)
nodes = index.as_retriever(similarity_top_k=10).retrieve("document")
print("Initial: ", [(node.text, node.node_id) for node in nodes])

# save the docstore/index store
index.storage_context.persist(persist_dir="./storage")

# load the index
new_storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir="./storage")

from llama_index import load_index_from_storage
# optional service context
loaded_index = load_index_from_storage(new_storage_context) # , service_context=service_context)

# test and confirm single document is retrieved
nodes = loaded_index.as_retriever(similarity_top_k=10).retrieve("document")
print("Loaded: ", [(node.text, node.node_id) for node in nodes])

# test that refresh works
documents = [Document(text="new document 1", doc_id="doc1"), Document(text="document 2", doc_id="doc2")]
loaded_index.refresh_ref_docs(documents)

# test and confirm refreshed documents are retrieved
nodes = loaded_index.as_retriever(similarity_top_k=10).retrieve("document")
print("Refreshed: ", [(node.text, node.node_id) for node in nodes])
```

**Comment by lauraceconi** [comment] 2023-12-19 09:50
Hi @logan-markewich 👋  I can see this is a duplicate of https://github.com/run-llama/llama_index/issues/9172. I'm having the same issue, and even implementing your solution, it quite didn't work for Elasticsearch. Do you have plans to implement the refresh function also to vector DBs?

**Comment by logan-markewich** [comment] 2023-12-19 13:50
@lauraceconi no plans currently. The example a above should work just fine for elastic tbh. 

But I think an easier method now is to use an ingestion pipeline (although elastic miiiiight need its base class updated to work with ingestion pipelines)

https://docs.llamaindex.ai/en/stable/examples/ingestion/document_management_pipeline.html

**Comment by cmosguy** [comment] 2024-03-22 15:00
> @3chospirits the docstore (which is used to track uploaded documents) isn't used by default when using a 3rd party vector db
> 
> This is because the entire index ends up getting stored in the vector db. This simplifies storage a lot, at the cost of this feature not working by default.
> 
> If you want, you can override this, but then you need to manage a docstore object and it's storage
> 
> Here's an example I had floating around that uses chroma, but PostgreSQL will be similar
> 
> ```python
> from llama_index import VectorStoreIndex, StorageContext, Document
> from llama_index.vector_stores import ChromaVectorStore
> 
> import chromadb
> db = chromadb.PersistentClient(path="./chroma_db")
> chroma_collection = db.get_or_create_collection("quickstart")
> vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
> 
> storage_context = StorageContext.from_defaults(vector_store=vector_store)
> 
> documents = [Document(text="document 1", doc_id="doc1")]
> 
> # test and confirm single document is retrieved
> index = VectorStoreIndex.from_documents(documents, storage_context=storage_context, store_nodes_override=True)
> nodes = index.as_retriever(similarity_top_k=10).retrieve("document")
> print("Initial: ", [(node.text, node.node_id) for node in nodes])
> 
> # save the docstore/index store
> index.storage_context.persist(persist_dir="./storage")
> 
> # load the index
> new_storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir="./storage")
> 
> from llama_index import load_index_from_storage
> # optional service context
> loaded_index = load_index_from_storage(new_storage_context) # , service_context=service_context)
> 
> # test and confirm single document is retrieved
> nodes = loaded_index.as_retriever(similarity_top_k=10).retrieve("document")
> print("Loaded: ", [(node.text, node.node_id) for node in nodes])
> 
> # test that refresh works
> documents = [Document(text="new document 1", doc_id="doc1"), Document(text="document 2", doc_id="doc2")]
> loaded_index.refresh_ref_docs(documents)
> 
> # test and confirm refreshed documents are retrieved
> nodes = loaded_index.as_retriever(similarity_top_k=10).retrieve("document")
> print("Refreshed: ", [(node.text, node.node_id) for node in nodes])
> ```

@logan-markewich 

I just want to clarify one more time.  If I understand correctly, when using ChromaDB to store my vector embeddings and text, I still need a separate `docstore` or in this case a `persistdir` to store what documents are loaded?  

Does this defeat the purpose of having ChromaDB in the first place?  Is the `persistdir` saving all the embeddings as well and causing duplication?  I wanted to use the `refresh()` feature as part of my pipeline, so I am very confused as to what what is the best strategy.

**Comment by logan-markewich** [comment] 2024-03-23 01:49
The docstore does not store embeddings nor does it perform vector search

**Comment by logan-markewich** [comment] 2024-03-23 01:50
IMO the best strategy is using an ingestion pipeline with a vectorstore and docstore attached (as mentioned above)

There are a few remote docstores, mongodbd, redis, postgres

**Comment by logan-markewich** [comment] 2024-03-23 01:52
The docstore in the case of an ingestion pipeline I'd just storing information needed to efficiently do a refresh. Vectordbs do not easily expose apis to do this (i.e. needing to map which nodes belong to which parent document, and comparing/updating as needed), hence the extra layer on top

**Comment by cmosguy** [comment] 2024-03-23 18:58
Thanks @logan-markewich , I am using your advice now and created an ingestion pipeline. I'm basically using a local simple docstore to manage what documents are chunked and embedded.

I would recommend to force users to implement the docstore somehow instead of disabling by default when using 3rd party Vector DBs. This makes first time users aware of such systems when learning about llama index.

Thanks again for the help!

**Comment by logan-markewich** [comment] 2024-03-23 21:45
I think forcing it would break a lot of existing code. Maybe a warning at least.

Glad it works 👍

**Closed by logan-markewich** 2024-03-23 21:45 UTC
Labels: bug, triage
